import { StickerPack } from '@matrix-messenger/core';

// Locally bundled stickers that ship with the client. These act as defaults
// before the homeserver synchronises remote packs.
export const LOCAL_STICKER_PACKS: StickerPack[] = [
  {
    id: 'local.twemoji',
    name: 'Twemoji',
    description: 'Default emoji-style stickers',
    source: 'local',
    isEmojiPack: true,
    avatarUrl: 'https://twemoji.maxcdn.com/v/latest/svg/1f60a.svg',
    stickers: [
      {
        id: 'smile',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f60a.svg',
        body: '😊',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':smile:'],
        emoji: ['😊'],
      },
      {
        id: 'laugh',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f602.svg',
        body: '😂',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':joy:'],
        emoji: ['😂'],
      },
      {
        id: 'wink',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f609.svg',
        body: '😉',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':wink:'],
        emoji: ['😉'],
      },
      {
        id: 'heart_eyes',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f60d.svg',
        body: '😍',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':heart_eyes:'],
        emoji: ['😍'],
      },
      {
        id: 'cool',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f60e.svg',
        body: '😎',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':sunglasses:'],
        emoji: ['😎'],
      },
      {
        id: 'cry',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f622.svg',
        body: '😢',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':cry:'],
        emoji: ['😢'],
      },
      {
        id: 'angry',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f621.svg',
        body: '😡',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':angry:'],
        emoji: ['😡'],
      },
      {
        id: 'thinking',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f914.svg',
        body: '🤔',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':thinking:'],
        emoji: ['🤔'],
      },
      {
        id: 'celebrate',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f389.svg',
        body: '🎉',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':tada:'],
        emoji: ['🎉'],
      },
      {
        id: 'rocket',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f680.svg',
        body: '🚀',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':rocket:'],
        emoji: ['🚀'],
      },
      {
        id: 'fire',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f525.svg',
        body: '🔥',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':fire:'],
        emoji: ['🔥'],
      },
      {
        id: 'ghost',
        url: 'https://twemoji.maxcdn.com/v/latest/svg/1f47b.svg',
        body: '👻',
        info: { w: 128, h: 128, mimetype: 'image/svg+xml', size: 1024 },
        shortcodes: [':ghost:'],
        emoji: ['👻'],
      },
    ],
  },
];
